### ISSUE TITLE
IM 消息处理时空指针

### ISSUE THREAD

**Issue by Zxilly** [Clansty/superstar-checkin#14]
```
[2022/4/28 1:42:05][ERROR] 处理 IM 消息时出现异常，可能不是活动消息 TypeError: Cannot read properties of undefined (reading 'includes')
    at exports.default (/app/handlers/handleEasemobMessage.js:32:44)
    at e.onTextMessage (/app/providers/easemob.js:69:44)
    at p (/app/sdk/Easemob-chat-3.6.3.js:2:41491)
    at e.N._metapayload (/app/sdk/Easemob-chat-3.6.3.js:2:97133)
    at E.y.onmessage (/app/sdk/Easemob-chat-3.6.3.js:2:170528)
    at E.o.dispatchEvent (/app/sdk/Easemob-chat-3.6.3.js:2:72283)
    at /app/sdk/Easemob-chat-3.6.3.js:2:188907
    at Array.forEach (<anonymous>)
    at E._transportMessage (/app/sdk/Easemob-chat-3.6.3.js:2:188872)
    at u.i.emit (/app/sdk/Easemob-chat-3.6.3.js:1:4270)
```
Docker 运行的，没 sourcemap 可能不太好定位。

**Comment by clansty** [comment]
这个没关系，不影响签到。毕竟后端返回消息没法完全找到规律的

**Comment by Zxilly** [comment]
我附加sourcemap调了下，是config的问题，我加个检查
