### ISSUE TITLE
docker 一直在报错

### ISSUE THREAD

**Issue by monocolotion** [Clansty/superstar-checkin#36]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

    at new NodeError (node:internal/errors:387:5)

    at validateString (node:internal/validators:121:11)

    at Object.isAbsolute (node:path:1157:5)

    at VirtualFS.mapToBase (/app/.pnp.cjs:5705:24)

    at VirtualFS.mkdirSync (/app/.pnp.cjs:5542:39)

    at PosixFS.mkdirSync (/app/.pnp.cjs:5542:24)

    at URLFS.mkdirSync (/app/.pnp.cjs:5542:24)

    at createDataDir (/app/.yarn/cache/oicq-npm-2.3.1-3c9e6879fd-7f15733fdb.zip/node_modules/oicq/lib/client.js:574:12)

    at new Client (/app/.yarn/cache/oicq-npm-2.3.1-3c9e6879fd-7f15733fdb.zip/node_modules/oicq/lib/client.js:49:21)

    at /app/providers/bot.js:14:11 {

  code: 'ERR_INVALID_ARG_TYPE'

}
禁用机器人组件后恢复正常了

**Comment by 1a2b3clong** [comment]
我也遇到了这样的问题，兄弟解决了没

**Comment by ghost** [comment]
同样的问题，如果想开机器人该怎么办呢
https://github.com/Clansty/superstar-checkin/issues/44 不知道能不能fork一份按照这个issue改一下然后自己弄个镜像compose🤔

**Comment by clansty** [comment]
如果知道怎么修复，可以发一个 PR
