### ISSUE TITLE
node.js调试时输入yarn start报错

### ISSUE THREAD

**Issue by w-p-li** [Clansty/superstar-checkin#39]
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.toPortablePath (E:\GitHup\xuexitong\superstar-checkin-main\.pnp.cjs:3066:9)       
    at PosixFS.mapToBase (E:\GitHup\xuexitong\superstar-checkin-main\.pnp.cjs:5637:18)
    at PosixFS.mkdirSync (E:\GitHup\xuexitong\superstar-checkin-main\.pnp.cjs:5542:39)
    at URLFS.mkdirSync (E:\GitHup\xuexitong\superstar-checkin-main\.pnp.cjs:5542:24)
    at createDataDir (E:\GitHup\xuexitong\superstar-checkin-main\.yarn\cache\oicq-npm-2.3.1-3c9e6879fd-7f15733fdb.zip\node_modules\oicq\lib\client.js:574:12)
    at new Client (E:\GitHup\xuexitong\superstar-checkin-main\.yarn\cache\oicq-npm-2.3.1-3c9e6879fd-7f15733fdb.zip\node_modules\oicq\lib\client.js:49:21)
    at E:\GitHup\xuexitong\superstar-checkin-main\build\providers\bot.js:14:11
    at new Promise (<anonymous>)
    at loginBot (E:\GitHup\xuexitong\superstar-checkin-main\build\providers\bot.js:11:24)       
    at E:\GitHup\xuexitong\superstar-checkin-main\build\index.js:40:30

**Comment by clansty** [comment]
不支持 Windows，请用 Linux 部署
